from typing import Any

class Small_LLM_Model:
    def __init__(self, model_name: str) -> None: ...
    def encode(self, text: str) -> Any: ...
    def decode(self, ids: list[int]) -> str: ...
    def get_logits_from_input_ids(
        self, input_ids: list[int]
    ) -> list[float]: ...
    def get_path_to_tokenizer_file(self) -> str: ...
    def get_path_to_vocab_file(self) -> str: ...
